### ISSUE TITLE
Does it work with Pushpin?

### ISSUE THREAD

**Issue by msumit** [fanout/pygripcontrol#4]
Not sure, if I am doing something wrong, but I can't make it work with Pushpin so far. For the context I am running pushpin locally and trying to publish to the "test" channel. 

`>>> grippub = GripPubControl({'control_uri': 'http://localhost:5561/'})`
`>>> grippub.publish_http_stream('test', 'Test publish python!')`

But I get nothing at the other end, though my local pushpin works with pushes from curl. Any help would be highly appreciated.

**Comment by jkarneges** [comment]
It is supposed to work with Pushpin, yes.

By default, the publishing happens asynchronously and hides errors. To investigate, try passing `blocking=True` to the publish call, which will make errors raise an exception.

**Comment by msumit** [comment]
Thanks @jkarneges for reply. I tried passing `blocking=True` and it just never returns. On hitting control-c, it gives following output:

```
>>> grippub.publish_http_stream('test', 'Test publish python!', blocking=True)

^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.12-intel/egg/gripcontrol/grippubcontrol.py", line 87, in publish_http_stream
  File "build/bdist.macosx-10.12-intel/egg/pubcontrol/pubcontrol.py", line 167, in publish
  File "build/bdist.macosx-10.12-intel/egg/pubcontrol/pubcontrolclient.py", line 112, in publish
  File "build/bdist.macosx-10.12-intel/egg/pubcontrol/pubcontrolclient.py", line 228, in _pubcall
  File "build/bdist.macosx-10.12-intel/egg/pubcontrol/pubcontrolclient.py", line 236, in _make_http_request
  File "/Users/sumitm/work/pygripcontrol/venv/lib/python2.7/site-packages/requests-2.18.4-py2.7.egg/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/sumitm/work/pygripcontrol/venv/lib/python2.7/site-packages/requests-2.18.4-py2.7.egg/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/sumitm/work/pygripcontrol/venv/lib/python2.7/site-packages/requests-2.18.4-py2.7.egg/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/sumitm/work/pygripcontrol/venv/lib/python2.7/site-packages/requests-2.18.4-py2.7.egg/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/sumitm/work/pygripcontrol/venv/lib/python2.7/site-packages/urllib3-1.22-py2.7.egg/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/sumitm/work/pygripcontrol/venv/lib/python2.7/site-packages/urllib3-1.22-py2.7.egg/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
```

**Comment by jkarneges** [comment]
What version of Pushpin?

It looks like the trailing slash on the control URI is at least one problem. For me, it causes a POST to be made to `//publish/`, resulting in 404. If I remove the slash then publishing works.

**Comment by msumit** [comment]
Hi @jkarneges,

Im using `pushpin 1.17.1`. Also, tried with and without slash, outcome is same.

**Comment by jkarneges** [comment]
Very weird. Can you run pushpin with `--verbose`, and show me lines from `pushpin-handler.log` when a publish is attempted?

**Comment by msumit** [comment]
@jkarneges plz see the logs here https://pastebin.com/fVDTYrJc. 

I've posted the logs of normal curl post and sdk post. In normal curl post, I get the message at receiver end, but in case of sdk, I get nothing.

**Comment by msumit** [comment]
@jkarneges one more thing I just realized, that whenever I do a curl post, my receiver gets the old messages which were posted via sdk as well. So it seems that those messages were left in queue, and get delivered via curl push only.

**Comment by jkarneges** [comment]
Logs look good. I think I know why you're seeing the queuing effect. The message you're publishing via the sdk doesn't have a newline, and if you use curl to listen to the stream then it will probably be line buffered. So I think the message probably got delivered, but is buffered inside curl, and only seen in the terminal once you publish another message containing a newline.

This doesn't explain why the sdk publish call would hang though (is it still hanging for you?), but hopefully the publish is getting delivered.

**Comment by msumit** [comment]
Thanks a lot @jkarneges. A new line in the message fixed the issue, and sdk works just fine with or without blocking parameter.
